# This file was generated by GoReleaser. DO NOT EDIT.
cask "beancount-cli" do
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_darwin_amd64.tar.gz"
      sha256 "f1379f8278a47fc09b2bf3f546da01423e9c10ed466b24b68d56a63ee0fc93a5"
    end
    on_arm do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_darwin_arm64.tar.gz"
      sha256 "e633fda67b93841fffa98db8efeea63beb58260135dcf488d78e6caa8da776f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_linux_amd64.tar.gz"
      sha256 "b9336fc54de77d515969e0ae5d44d220d827d7345f76ce919899aace49d53d3d"
    end
    on_arm do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_linux_arm64.tar.gz"
      sha256 "d92d271a17ce285f912f883cffc8246119571d9ab2db6c4640b0a347cb267c20"
    end
  end

  name "beancount-cli"
  desc "Official CLI for Beancount — authenticate and manage your ledgers from the terminal."
  homepage "https://beancount.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beancount-cli"

  # No zap stanza required

end
