# This file was generated by GoReleaser. DO NOT EDIT.
cask "beancount-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_darwin_amd64.tar.gz"
      sha256 "62e8ca76a23fb690722d668ec018e5a15625315d81ebfc11fe2fcb451b6f933f"
    end
    on_arm do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_darwin_arm64.tar.gz"
      sha256 "0cf6dea8807471afb820866d02adae54b023653bb807e416fa0e9e252090a148"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_linux_amd64.tar.gz"
      sha256 "34b8ba87d256f79eb94d6b714adf40554956dde4aa1cf58e7cbf6b476b59a6a4"
    end
    on_arm do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_linux_arm64.tar.gz"
      sha256 "4273059e3acf920daa83b3888ba00c79e970069b883757ad9b21ed887bec93dc"
    end
  end

  name "beancount-cli"
  desc "Official CLI for Beancount — authenticate and manage your ledgers from the terminal."
  homepage "https://beancount.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beancount-cli"

  # No zap stanza required

end
