# This file was generated by GoReleaser. DO NOT EDIT.
cask "beancount-cli" do
  version "0.1.10"

  on_macos do
    on_intel do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_darwin_amd64.tar.gz"
      sha256 "f8a6dc70930fa7951a82af2fcbea5d07d9533eac77ce07c28d14913e459a86f1"
    end
    on_arm do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_darwin_arm64.tar.gz"
      sha256 "ee3b12e2ce3797ada9d5525d10727708e3635c082e7f7bd5edf8cc51385cae4e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_linux_amd64.tar.gz"
      sha256 "55851204a5d5c30ba46b05644a2116778b56f96ed33e8bdfced8921400c3b303"
    end
    on_arm do
      url "https://github.com/stargately/beancount-cli/releases/download/v#{version}/beancount-cli_linux_arm64.tar.gz"
      sha256 "b712c21775f134202725442cd57bfb813aaaad44e55da0aebaad5c219c26bbf7"
    end
  end

  name "beancount-cli"
  desc "Official CLI for Beancount — authenticate and manage your ledgers from the terminal."
  homepage "https://beancount.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beancount-cli"

  # No zap stanza required

end
